### ISSUE TITLE
请问套餐流量减半指？

### ISSUE THREAD

**Issue by xtvjxk123456** [cgsss/forum#10]
用户持有的总流量减半还是服务器本身的流量减半（我看公告说有服务器没流量了..）

**Comment by cgsss** [comment]
购买的套餐流量减半，以前是1个月100G，之后改成50G，公告说的服务器没流量了跟这个没关系，这个是因为那个节点所在机房有流量限制，本月的使用量已经满了，所以节点被停了，然后13号流量会重置，就又可以用了。
