### ISSUE TITLE
会不会把我的手机里面的照片给删除了

### ISSUE THREAD

**Issue by lalaku01** [cgsss/forum#12]
![_20171101190314](https://user-images.githubusercontent.com/25317766/32272080-8274dd00-bf37-11e7-89ed-4302df955e31.jpg)
![_20171101190314](https://user-images.githubusercontent.com/25317766/32272135-bb6362d0-bf37-11e7-8e5a-4c36627e203c.jpg)

**Comment by cgsss** [comment]
不是退出icloud，是退出app store里的apple账户
