### ISSUE TITLE
share IP

### ISSUE THREAD

**Issue by bxforever** [cgsss/forum#15]
在youtube上搜索显示share IP,vimeo上搜索没问题

**Comment by bxforever** [comment]
搜索后跳至"我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求"

**Comment by cgsss** [comment]
你用的哪个节点？

**Comment by bxforever** [comment]
新加坡 日本 香港几个都试过,今天发现highlight3D也上不去

**Comment by cgsss** [comment]
我这都正常，目测这跟我们没关系，highlight3d 今天他们网站出故障了，官方出了一个故障提示，你换台电脑或手机上再试试。

**Comment by bxforever** [comment]
好的,我试试,thx~

**Comment by cgsss** [comment]
OK，不客气

**Comment by cgsss** [comment]
之前没理解这个具体是哪个问题，这个情况是不能避免的，主要原因是我们所购买的主机ip被以前的用户拿来做过youtube的爬虫工作，youtube会有反爬虫机制，从而导致在youtube上搜索时出现人机验证现象，如果要彻底避免此类情况解决办法只能是我们去更换主机的ip，但服务商的ip不是你可以随便换的，即使你申请一次更换ip，但新的ip也会随机产生，不能排除该ip曾经没有爬过youtube的内容，所以只能用户去勾选一下 人机验证的选项就行，在一段时间内就不会再次出现人机验证现象了。
 
而google主页搜索如果出现人机验证现象，你们可以访问ipv6.google.com避免此类情况，这个我们的节点列表和线路选择里很早就提示过了。
