### ISSUE TITLE
连不上了

### ISSUE THREAD

**Issue by srsyzhenge** [cgsss/forum#17]
突然之间就连不上了，希望告知解决方法。QQ 1765869818.谢谢

**Comment by cgsss** [comment]
不好意思，没有及时回复，我看您账户最近使用时间离现在挺近的，问题应该解决了吧？

**Comment by srsyzhenge** [comment]
您好，公司的电脑可以连了，家里的电脑昨晚试了下 还是不能连，是哪里设置错了吗，主家里的CGsss官网登不了 不知道怎么设置

**Comment by cgsss** [comment]
#2 这里面先过一遍

**Comment by srsyzhenge** [comment]
谢谢 我周末回去试试

**Comment by cgsss** [comment]
ok
