### ISSUE TITLE
没有360和百度东西依然被ban

### ISSUE THREAD

**Issue by zml1988331** [cgsss/forum#19]
已经很久了，一直被禁用，想知道你们那里有显示是访问了什么吗，发邮件也没回复。我只有百度云盘。360都卸载了。我得注册邮箱417xxx709@qq.com

**Comment by cgsss** [comment]
我们这边看到的记录和你看到的是一样的，不能访问你系统查看具体是啥进程来通信的哦，你看下https://github.com/cgsss/forum/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8#14-%E5%B7%B2%E7%BB%8F%E5%8D%B8%E8%BD%BD%E4%BA%86360%E7%9B%B8%E5%85%B3%E8%BD%AF%E4%BB%B6%E8%B4%A6%E6%88%B7%E4%BE%9D%E7%84%B6%E8%A2%AB%E7%A6%81%E7%94%A8

**Comment by zml1988331** [comment]
检查后台通信然后哪个是360的？都是网址数字

**Comment by cgsss** [comment]
你谷歌下：如何彻底卸载360 呢

**Comment by zml1988331** [comment]
其实是否可以有空写个卸载360的教程，主要这个太普遍了问题

**Comment by cgsss** [comment]
主要我这边没有可测试的机器，即使安装360产品，也没出现不能完全卸载的情况，不知道用户的电脑是怎么使用导致不能完全卸载的。
