### ISSUE TITLE
Buy hot issues 

### ISSUE THREAD

**Issue by dogandogan** [cgsss/forum#21]
I bought a year's member on the CG SSS platform, but I didn't contact the seller, no filling code.

**Comment by dogandogan** [comment]
![image](https://user-images.githubusercontent.com/34412480/33803131-5de1c304-ddc3-11e7-8aa8-a37132806376.png)

**Comment by cgsss** [comment]
Hi, The code is already in your uploaded image, You can use this code to buy packages on the website, We've hidden the pictures you uploaded for security reasons.
