### ISSUE TITLE
关于时间

### ISSUE THREAD

**Issue by bxforever** [cgsss/forum#22]
17年11月购买了一年到期时间是18年11月，12月再次购买一年充值后到期时间显示是19年11月？不是应该19年12月吗？

**Comment by cgsss** [comment]
请具体到日来计算，我们的一年设定的是365天，每年都有闰月闰年，按月来算是不准确的

**Comment by cgsss** [comment]
你12月购买就该是19年11月啊，这个时间是在你已购套餐的到期时间上累计，除非现在是18年12月，你购买一年到期时间才应该是19年12月。

**Comment by bxforever** [comment]
额...不好意思,脑子短路了.

**Comment by cgsss** [comment]
没关系的，如遇到其他问题欢迎再次提交问答，工作时间内我们会及时解决。
