### ISSUE TITLE
充值并购买套餐后，仍然显示账户已到期？？

### ISSUE THREAD

**Issue by qzwbla** [cgsss/forum#24]
![image](https://user-images.githubusercontent.com/35020621/34474647-f5d1c744-efbc-11e7-8519-ad0db8c6d148.png)

**Comment by cgsss** [comment]
你购买的是流量，不是套餐，流量不能延长使用时间的

**Comment by qzwbla** [comment]
那现在可以退款不？

**Comment by cgsss** [comment]
你要重新购买会员的话，我可以给你把余额调整回去，
如果不购买的话，请提供你支付宝账号

**Comment by qzwbla** [comment]
支付宝账号：qzwbla@163.com，谢谢！

**Comment by qzwbla** [comment]
效率很高，试用体验也非常棒，谢谢！

**Comment by cgsss** [comment]
余额已经给你返回去了，你重新购买套餐只需要再购买充值码补足套餐需要的额度就行了，就不用走支付宝了。
