### ISSUE TITLE
今充值后普通端口仍无法连接

### ISSUE THREAD

**Issue by meilihao** [cgsss/forum#25]
昨天会员到期(原先正常), 今购买年会员后仍无法连接, 我就重置端口,还是连不上. ss-local未报错, chrome报`ERR_CONNECTION_RESET`.

**Comment by cgsss** [comment]
普通端口很早就不开放了

**Comment by cgsss** [comment]
给你开放新的端口了，你试一下哈，之后别随便重置端口了，不然需要我们重新开放新的端口才行。连接不上的问题一般跟端口没什么关系

**Comment by meilihao** [comment]
@cgsss  主要是今天充值后也不知为什么还是不能连接,才去重置端口, 已测试连接恢复了.
