### ISSUE TITLE
求教:请问游戏模式是什么？怎么用？

### ISSUE THREAD

**Issue by xtvjxk123456** [cgsss/forum#26]
请问

![qq20180103-201148](https://user-images.githubusercontent.com/28707826/34520139-66e5fe72-f0c2-11e7-9508-09c9d0187af0.png)

这个怎么理解，和平时买的什么加速器一样么？

咱们的服务可以当游戏加速器么？

**Comment by cgsss** [comment]
服务器是支持udp的，自然就支持游戏加速，但ssr的客户端默认udp这块比较弱

目前大家用得比较多的是SSTap
下载地址：https://www.sockscap64.com/sstap/

由于udp的代理稳定性会受到各个地区的ISP服务商的干扰，我们没有把心思放在服务游戏玩家上，具体使用还请google。

**Comment by xtvjxk123456** [comment]
哦哦，那我还是买别的专门加速器吧,多谢多谢!!

**Comment by cgsss** [comment]
不客气
