### ISSUE TITLE
买错东西，买成流量包了 能退回重新买吗

### ISSUE THREAD

**Issue by qq1064618734** [cgsss/forum#27]
提交问题前的注意事项：

1. 遇到服务器连接不上，请首先查看公告。

2. 请先在 常见问题列表 和 已解决问题列表 中查看是否有同类情况。
  - 常见问题列表：https://github.com/cgsss/forum/wiki/
  - 已解决问题列表：https://github.com/cgsss/forum/issues?q=is%3Aissue+is%3Aclosed
  
3. 本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。
  - 本站网址
  - 本站节点的任何信息
  - 您的账户邮箱（如123456789@qq.com可改成123xxx789@qq.com填写（后台可以模糊查询到您的账户信息））

如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）。

阅读完以上信息后，您可清空该内容并填写您的问题详情。

**Comment by qq1064618734** [comment]
![Uploading QQ截图20180110222129.png…]()

**Comment by qq1064618734** [comment]
![image](https://user-images.githubusercontent.com/35300952/34777302-d9d1a9d0-f654-11e7-8eec-598b591e415b.png)
![qq 20180110222129](https://user-images.githubusercontent.com/35300952/34777305-dbc34a8c-f654-11e7-92e2-5b2b236d66b9.png)

**Comment by jeanim** [comment]
已退回

**Comment by cgsss** [comment]
已退回，请登录查看
