### ISSUE TITLE
为什么其他网站都能上，就是GOOGLE上不了

### ISSUE THREAD

**Issue by Starsyiyiyi** [cgsss/forum#28]
youtube都能连接和观看视频，但是一切和GOOGLE沾边的网站就连接不上.HOSTS也清空过不行

**Comment by cgsss** [comment]
你访问 https://ipv6.google.com 试试呢

**Comment by Starsyiyiyi** [comment]
下载图是在哪里的呢？IPV6这个就正常.https://www.google.com就不行

**Comment by cgsss** [comment]
你qq截下图存到桌面后，直接把图扔到这个留言框里 等会 就可以评论进来了

**Comment by Starsyiyiyi** [comment]
![qq 20180112004332](https://user-images.githubusercontent.com/35342150/34836047-a5db2e8e-f731-11e7-9262-76f4514cd4ab.jpg)

**Comment by cgsss** [comment]
你试试下面的操作呢：
1. 换个浏览器
2. 清理浏览器缓存
3. 重启ssr软件
4. 切换节点（不勾选节点均衡）

**Comment by Starsyiyiyi** [comment]
我用chrome和ie都不行，切换了节点也不行

**Comment by cgsss** [comment]
那你用手机或者其他电脑呢，分别在路由器环境下和非路由器环境下试试，看看是否依然如此？ps: 我们的设备上没有出现此类情况。
