### ISSUE TITLE
充值页面打不开

### ISSUE THREAD

**Issue by Justin0345** [cgsss/forum#29]
提交问题前的注意事项：

1. 遇到服务器连接不上，请首先查看公告。

2. 请先在 常见问题列表 和 已解决问题列表 中查看是否有同类情况。
  - 常见问题列表：https://github.com/cgsss/forum/wiki/
  - 已解决问题列表：https://github.com/cgsss/forum/issues?q=is%3Aissue+is%3Aclosed
  
3. 本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。
  - 本站网址
  - 本站节点的任何信息
  - 您的账户邮箱（如123456789@qq.com可改成123xxx789@qq.com填写，后台可模糊查询）

如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）。

阅读完以上信息后，您可清空该内容并填写您的问题详情，如需上传截图，拖拽图片到本编辑器中中即可。

**Comment by cgsss** [comment]
现在正常了

**Comment by Justin0345** [comment]
还是不能

**Comment by cgsss** [comment]
我这能打开，只是加载没以前快，你打开后稍等会呢，我们马上把备用购买页面加上去

**Comment by cgsss** [comment]
页面已经正常，本帖关闭，以后如果遇到此类情况，一般等等就好了（此类情况可能一年中会出现几次）
