### ISSUE TITLE
如何给PS4使用？

### ISSUE THREAD

**Issue by Starsyiyiyi** [cgsss/forum#31]
有没有教程呢？

**Comment by cgsss** [comment]
你是需要下载游戏的时候提速还是说游戏中要加速？
如果是下载游戏安装包提速，设置下本地代理->允许从局域网的客户端访问,然后再ps4里连接你的电脑访问外网，但这个仅限于http的访问，
如果是游戏中加速，用ssr的pc客户端可能不会很理想，需要你在路由器里安装ssr的客户端然后走游戏模式，或参考本站内的图文教程https://www.cgsss.net/help/?/article/8，如出现于固件相关的问题，还请谷歌：“梅林固件 SSR”

**Comment by Starsyiyiyi** [comment]
需不需要在同一个IP段内？

**Comment by Starsyiyiyi** [comment]
还有就是开了局域网代理，电脑重启后就只能上QQ，所有网站都打不开，开SSR，或者关闭代理才行

**Comment by cgsss** [comment]
理论上在一个局域网里就行，最好是在同一个ip段，不同的话你可以看下表现情况如何

一般来说ssr都会设置为电脑启动后自动启动，因为会修改ie里的代理配置，如果不开启就需要手动把ie里的代理配置关掉
![qq20180119-000024](https://user-images.githubusercontent.com/28707826/35107402-c72b5aa8-fcab-11e7-9e2e-5eff87a26fff.png)

**Comment by cgsss** [comment]
然后QQ之所以能上，主要因为QQ使用UDP+TCP协议传输，即使TCP不通也能通过UDP传输数据。

注：[QQ 为什么以 UDP 协议为主，以 TCP 协议为辅？](https://www.zhihu.com/question/20292749)

**Comment by Starsyiyiyi** [comment]
设置代理那个账号密码需要填写吗

**Comment by cgsss** [comment]
这个无所谓的，设置下也就是你在ps4里也需要填一下，不设置在ps4里应该输入ip和端口就能连，不过具体情况你需要自行测试。
