### ISSUE TITLE
路由器SSR怎么设置呢？

### ISSUE THREAD

**Issue by Starsyiyiyi** [cgsss/forum#32]
我没有看到IP地址呀？在哪里知道服务器IP地址？

**Comment by Starsyiyiyi** [comment]
还有那个是游戏模式呀
![image](https://user-images.githubusercontent.com/35342150/35439101-36db4fce-02d4-11e8-9ac1-ea44cedf1074.png)

**Comment by cgsss** [comment]
ip地址你不需要知道，服务器地址你填我们的节点域名就行了，在节点列表里点击节点就可以看到。
这个是工作模式跟游戏模式没关系，请查看常见问题列表里，了解之间的区别，gfwlist=pac模式，游戏模式不在这个页面里设置，梅林固件里有个设置dns解析的页面，你可以参考使用说明里的教程参考下（不是最新）

**Comment by Starsyiyiyi** [comment]
执行之后出现
Jan 26 20:11:51 dnsmasq[9285]: started, version 2.76 cachesize 1024
Jan 26 20:11:51 dnsmasq[9285]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Jan 26 20:11:51 dnsmasq-dhcp[9285]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Jan 26 20:11:51 dnsmasq-dhcp[9285]: DHCP, sockets bound exclusively to interface br0
Jan 26 20:11:51 dnsmasq[9285]: read /etc/hosts - 3 addresses
Jan 26 20:11:51 dnsmasq[9285]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan 26 20:11:51 dnsmasq-dhcp[9285]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan 26 20:11:51 【SS】: ss-redir stop.
然后就停止，是什么错误呀？

**Comment by Starsyiyiyi** [comment]
好了自己解决了，3Q

**Comment by Starsyiyiyi** [comment]
还有一个问题就是 端口填写主页的还是节点页面的？都不一样

**Comment by cgsss** [comment]
现在是单端口多用户模式，所有用户都在443端口，你个人账户的端口没用。

**Comment by Starsyiyiyi** [comment]
协议参数和混淆都填写节点页面的？

**Comment by cgsss** [comment]
对的，以节点列表里的为准

**Comment by Starsyiyiyi** [comment]
我发现我这里路由器设置没有协议没有auth_chain_a
怎么办？

**Comment by cgsss** [comment]
你是在SSR Server标签页里设置的么

**Comment by Starsyiyiyi** [comment]
并不是，但是也有SSR server页面

**Comment by Starsyiyiyi** [comment]
![image](https://user-images.githubusercontent.com/35342150/35440645-36802b88-02db-11e8-9abb-decc71ae77fa.png)

**Comment by cgsss** [comment]
SSR Server页面里有相关配置么，也有可能你路由器里安装的版本比较老了

**Comment by Starsyiyiyi** [comment]
![image](https://user-images.githubusercontent.com/35342150/35440758-c33ad1b8-02db-11e8-8a47-a94884384cce.png)

**Comment by cgsss** [comment]
哦，这个不对哈，这个是设置服务器的，那应该是你安装的版本比较老了，没有auth_chain_a协议（这个协议发布也比较长时间了），具体还请谷歌或者到固件的官网看看相关的同类问题。

**Comment by Starsyiyiyi** [comment]
必须要用这个协议么？ 可能我这个路由器不支持吧..没有其他办法解决吗？

**Comment by cgsss** [comment]
恩，必须用，你最好看看是不是有最新版的安装包，或者进这个固件的群里去问问。
