### ISSUE TITLE
现在还能使用SS吗？

### ISSUE THREAD

**Issue by Starsyiyiyi** [cgsss/forum#33]
还能使用SS吗？

**Comment by cgsss** [comment]
你指ss客户端么，目前不支持了。如果实在需要的话，需要我们单独给你把端口打开，然后你自己把加密和协议改成ss兼容的模式才能使用，但这个也仅限于新加坡4号节点，其他都不开放（安全因素考虑）

**Comment by Starsyiyiyi** [comment]
因为我家的WIFI不支持新的SSR协议，本来打算买来完怪物猎人世界，港服的老是掉线。路由器支持SS和SSR旧版的协议。

**Comment by cgsss** [comment]
你是刷的梅林固件么?

**Comment by Starsyiyiyi** [comment]
并不是，应为不是华硕，我用的是潘多拉的固件

**Comment by cgsss** [comment]
这个得你自己测试哪些固件上有最新的ssr才行了，然后查看估计和你的路由器的兼容性如何，关于路由器的配置，我们也只能做到点到为止，出现具体问题只能用户自己去解决，主要也是因为路由器的变数太多了，然后用户群体也都是面向开发者，普通用户很少会去折腾。

**Comment by Starsyiyiyi** [comment]
我已经找过我这个WIFI的，已经是固件最新了，但是还是不支持现在这里服务器的SSR协议，所以只能用SS了....

**Comment by cgsss** [comment]
估计最新跟ssr最新不是一回事哈，你需要安装最新版的ssr

**Comment by Starsyiyiyi** [comment]
然而我的路由器已经是最新版估计连，不支持这个混淆协议。用不了，能开SS吗？

**Comment by cgsss** [comment]
前面已经给你说过了，

`如果实在需要的话，需要我们单独给你把端口打开，然后你自己把加密和协议改成ss兼容的模式才能使用，但这个也仅限于新加坡4号节点，其他都不开放（安全因素考虑）`

你的账户是多少？

**Comment by cgsss** [comment]
账户邮箱是asdxxx85@163.com这个么
