### ISSUE TITLE
请问，我为什么只有新加坡2/4线路可以用，其他都不能用呢，公告好像也没有写了，还是我设置有什么问题了？

### ISSUE THREAD

**Issue by qinfc317** [cgsss/forum#36]
提交问题前的注意事项：

1. 遇到服务器连接不上，请首先查看公告。

2. 请先在 常见问题列表 和 已解决问题列表 中查看是否有同类情况。
  - 常见问题列表：https://github.com/cgsss/forum/wiki/
  - 已解决问题列表：https://github.com/cgsss/forum/issues?q=is%3Aissue+is%3Aclosed
  
3. 本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。
  - 本站网址
  - 本站节点的任何信息
  - 您的账户邮箱（如123456789@qq.com可改成123xxx789@qq.com填写，后台可模糊查询）

如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）。

阅读完以上信息后，您可清空该内容并填写您的问题详情，如需上传截图，拖拽图片到本编辑器中即可。

**Comment by cgsss** [comment]
你的用户等级不是普通用户吧？如果是普通用户，并且刚充了值，请在本站去购买下套餐，然后再更新下节点列表。

**Comment by cgsss** [comment]
您好，您的账户是38xxx42694@qq.com吧？刚看了下，您的等级被降级了，应该是之前自动续费的订单导致的，已经给您调整到年会员了

**Comment by qinfc317** [comment]
是这个账户，好像已经可以了，非常感谢~！

**Comment by cgsss** [comment]
不用谢哈，是我们的问题，现在给您调了一个月，账户有效期从 2019-03-21 22:54:53 调整为 2019-04-21 22:54:53了。之后如果遇到什么问题请及时提，我们会快速解决。
