### ISSUE TITLE
Linux如何配置翻墙

### ISSUE THREAD

**Issue by Aubin1024** [cgsss/forum#37]
Linux云主机如何配置翻墙？

**Comment by cgsss** [comment]
您是要自己搭服务器？还是说你的电脑是linux系统需要使用我们的服务呢

**Comment by Aubin1024** [comment]
你们的客户端由windows、安卓的，可是我们见到有linux的。
我想让我的linux主机能访问google

**Comment by cgsss** [comment]
linux你可以装下Shadowsocks-Qt5，然后我们给账户单独开通端口，其他节点不支持，没有写linux的教程，主要是默认我们认为用linux的用户可以自行google解决，但如果用户多了的话，我们可以把教程写上去。
