### ISSUE TITLE
服务器无法访问问题

### ISSUE THREAD

**Issue by Oliverhahaha** [cgsss/forum#38]
已经查看了公告，并未使用香港节点，链接了日本和新加坡节点都无法打开谷歌和台湾的“露天”网站，都是正常的网站，昨天都还可以正常访问。不是所有网站都不能上，国内不需要翻墙的网站都能正常使用。
我的账号是****hy007@163.com

**Comment by jeanim** [comment]
您的账号是正常的，所有节点都不能上？google能打开？

**Comment by cgsss** [comment]
您的账号是正常的，所有节点google都打不开？

**Comment by Oliverhahaha** [comment]
谷歌不能打开

**Comment by Oliverhahaha** [comment]
日本 新加坡 洛杉矶 都试了

**Comment by cgsss** [comment]
方便的话，您装一下teamviewer，然后截图给我，我这边远程您看一下

**Comment by Oliverhahaha** [comment]
好的

**Comment by nyjjky** [comment]
我的显示端口被占用，用不了

**Comment by Oliverhahaha** [comment]
密码改成65y5jk了 再试试

**Comment by cgsss** [comment]
@nyjjky 请看常见问题列表

**Comment by cgsss** [comment]
@Oliverhahaha 您没有关掉您以前的代理设置哈

**Comment by Oliverhahaha** [comment]
谢谢

**Comment by nyjjky** [comment]
打开客户端任务管理器显示有两个进程的？

**Comment by cgsss** [comment]
你改一下你现在的端口就行了，可能端口被其他的软件占用了，如果有两个同样的ssr进程，那就都退出然后重开一下

**Comment by nyjjky** [comment]
151 860 702   b41m2q 求设置

**Comment by nyjjky** [comment]
非常感谢
