### ISSUE TITLE
重装了机子，如何访问主页

### ISSUE THREAD

**Issue by xtvjxk123456** [cgsss/forum#40]
如题，软件都丢失了,访问不了主页了

**Comment by cgsss** [comment]
网站是正常的，你可以用手机访问试试。

**Comment by xtvjxk123456** [comment]
手机是正常的，我电脑没有软件可以翻墙了，如何访问主页,获取软件之类的

**Comment by cgsss** [comment]
电脑正常情况下直接就能访问我们的主页，如果不能访问，请确保你的电脑上的浏览器没有无效的代理设置。

**Comment by xtvjxk123456** [comment]
不行，无法访问cgsss.net

**Comment by cgsss** [comment]
不是长城宽带吧？我这边用电信不开代理就能访问主页

**Comment by xtvjxk123456** [comment]
忘了说了，我换了主板了，网卡应该算是换了吧？？

**Comment by cgsss** [comment]
![qq20180411-000918](https://user-images.githubusercontent.com/28707826/38568966-9beda718-3d1c-11e8-9433-3776fe44bcfb.png)
你看下你的IE浏览器里的代理设置是否和上图一样

更换硬件不影响，我们早就开放访问权限了，任何人都可以随时访问主页的。

**Comment by cgsss** [comment]
你看看你手机不开代理 能不能访问主页，如果能，那就是你电脑浏览器什么的有问题

**Comment by xtvjxk123456** [comment]
手机不开代理无法访问

**Comment by cgsss** [comment]
[ssr-win.zip](https://github.com/cgsss/forum/files/1895472/ssr-win.zip)
这个是软件，你可以直接下载，订阅地址你复制下手机上的到你电脑就行了

**Comment by xtvjxk123456** [comment]
不行，无法更新订阅

**Comment by cgsss** [comment]
![qq20180411-003502](https://user-images.githubusercontent.com/28707826/38570361-3f76b570-3d20-11e8-89a7-f5857063a088.png)
从上图能看到全国各地基本都能正常访问主页。

**Comment by xtvjxk123456** [comment]
我这边看来就是得开代理才能去官网

**Comment by xtvjxk123456** [comment]
操，突然能访问官网了

**Comment by xtvjxk123456** [comment]
不过还是无法更新订阅

**Comment by cgsss** [comment]
能访问官网的话，更新订阅的时候请选择不通过代理更新

**Comment by xtvjxk123456** [comment]
果然，官网还是无法访问，看来，和我这边能不能访问官网有关

**Comment by cgsss** [comment]
不能访问官网的话，肯定就不能订阅更新节点了

**Comment by xtvjxk123456** [comment]
早点休息吧，看来是不是我这边的问题，估计是网络运营商那边的问题,多谢大佬了，只能等网络好了再搞了

**Comment by cgsss** [comment]
恩，没事，有可能是网络阻塞引起，比如处于高峰期时段，带宽质量不佳访问境外服务器就会很卡，出现这种情况你也可以试试能不能访问artstation。

**Comment by xtvjxk123456** [comment]
a站是可以的

**Comment by cgsss** [comment]
![qq20180411-005117](https://user-images.githubusercontent.com/28707826/38571218-7bc11226-3d22-11e8-96d4-a92776867700.png)
我这边测速A站延迟比我们官网高一倍，而且伴随丢包。

**Comment by cgsss** [comment]
![qq20180411-005310](https://user-images.githubusercontent.com/28707826/38571300-b826d6a6-3d22-11e8-9099-ceef325d50b6.png)

我这边（电信100M）测速A站延迟比我们官网高一倍，而且伴随丢包。

**Comment by xtvjxk123456** [comment]
我显示没有丢包啊

**Comment by cgsss** [comment]
那你可以再用公司电脑测试看看，感觉是你的网络环境Qos严重，一般这种情况下大多数网站都会做CDN加速，不过由于安全因素，我们没搞这个，所以只能靠用户直连，目前看下来问题不大。

**Comment by xtvjxk123456** [comment]
公司一点问题都没有，好尴尬，等明天再看看吧，看来是网络问题

**Comment by cgsss** [comment]
只要不是100%丢包，网站应该是能正常打开并登陆的，只是打开会比较卡
