### ISSUE TITLE
为什么从昨天到现在都上不了，设置都是对的。

### ISSUE THREAD

**Issue by cansey** [cgsss/forum#42]
更新pac为GFwlist的时候出现了这个
![- --1](https://user-images.githubusercontent.com/39074262/39735336-bb692cd8-52ad-11e8-8df1-c25e708bed2f.jpg)

![- -1](https://user-images.githubusercontent.com/39074262/39735123-ae70570a-52ac-11e8-8eb5-6b6095408ec8.jpg)

昨天早上打开yo u t u b e在看了一个视频好好的，然后打开另外一个视频突然就上不了了，手机也登不上去。我没有动任何设置，我以为是我账号的问题，我就今早有买了一个号试试看，结果还是不行。手机提示好像连上了，但是就是没有流量动。电脑端的小飞机一直是绿色的好好，但是就是上不了。

**Comment by cgsss** [comment]
你的PAC不对，这个自动更新pac的功能已经不可用了，我们换成手动设置了，你只需要在 https://cgsss.net/help/?/article/13 这里根据教程拷贝文件到软件目录里即可。

目前默认情况下推荐用全局模式+绕过大陆和局域网的设置方式，pac的方式不太推荐了。

![image](https://user-images.githubusercontent.com/28707826/39735452-38d3b5c6-52ae-11e8-83fa-8c98198ee154.png)

**Comment by cansey** [comment]
替换了也不行，我全部都设置对了，还是不行。

**Comment by cansey** [comment]
![1](https://user-images.githubusercontent.com/39074262/39736127-5ac38226-52b1-11e8-8d7b-3ff98363ee5d.jpg)

**Comment by cansey** [comment]
没有用手机绑定的，重来没有，是不是别人绑定后，导致我的账户出问题

**Comment by cansey** [comment]
![qq 20180508112840](https://user-images.githubusercontent.com/39074262/39736497-cb5c6ed4-52b2-11e8-939c-2732c4795943.png)

**Comment by cgsss** [comment]
我们能查到绑定的手机号尾号为89，你的订单记录里我们也看到了尾号为89，如果您确定没有恶意操作的话，那就没事，主要能避免下次这样的恶意行为就好。

另外，我们的appleid账号设置了安全措施，找回也比较简单。

您传下teamviewer的截图，我们远程您看看。

**Comment by cgsss** [comment]
备注：问题已解决，原因是账号的加密和混淆设置为老的配置，导致客户端post请求加密数据错误。
