### ISSUE TITLE
我购买了半年会员，但是一天后还是显示到期了

### ISSUE THREAD

**Issue by xuxiaoxiao001** [cgsss/forum#45]
提交问题前的注意事项：

1. 遇到服务器连接不上，请首先查看公告。

2. 请先在 常见问题列表 和 已解决问题列表 中查看是否有同类情况。
  - 常见问题列表：https://github.com/cgsss/forum/wiki/
  - 已解决问题列表：https://github.com/cgsss/forum/issues?q=is%3Aissue+is%3Aclosed
  
3. 本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。
  - 本站网址
  - 本站节点的任何信息
  - 您的账户邮箱（如123456789@qq.com可改成123xxx789@qq.com填写，后台可模糊查询）

如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）。

阅读完以上信息后，您可清空该内容并填写您的问题详情，如需上传截图，拖拽图片到本编辑器中即可。

**Comment by cgsss** [comment]
您购买卡密后是否用卡密在我们网站充值？充值后是否购买了套餐呢？

**Comment by xuxiaoxiao001** [comment]
购买了 但是没有购买记录   而且卡密也不能用了

**Comment by cgsss** [comment]
您账号多少？

**Comment by xuxiaoxiao001** [comment]
504260571@qq.com

**Comment by cgsss** [comment]
![image](https://user-images.githubusercontent.com/28707826/40289422-c2bdf544-5cea-11e8-9f24-24bcfd3f1419.png)
这两个账号都是你把？你有一个账户余额没有使用

**Comment by xuxiaoxiao001** [comment]
好的   谢谢   啊

**Comment by cgsss** [comment]
不客气

**Comment by xuxiaoxiao001** [comment]
你好  顺便问一下啊   ios手机下载APP之后  路径填好之后   不会刷新出新的节点  只有一个

**Comment by cgsss** [comment]
你电脑上填写完订阅地址后可以刷新出所有节点列表？另外你使用的账户是否已经购买了套餐呢，如果账户级别为普通会员，理论上能刷出三个免费试用节点，购买套餐后，能刷新出12个节点。

**Comment by cgsss** [comment]
你电脑上填写完订阅地址后可以刷新出所有节点列表？另外你使用的账户是否已经购买了套餐呢，如果账户级别为普通会员，理论上能刷出三个免费试用节点，购买套餐后，能刷新出12个节点。
