### ISSUE TITLE
关于ios端shadowrocket收费的问题

### ISSUE THREAD

**Issue by kangmiaomi** [cgsss/forum#48]
现在使用你们的apple id下载软件，软件现在变更为收费软件，需要3.99$，我看到你们有余额，但是不问自取显然不太好，所以想问问你们能不能买下这个软件，方便下载，我这边也并不能付费

**Comment by cgsss** [comment]
我们已经买了的，你需要登录账户后，在账户的隐藏列表里去下载（之前在已购项目里，但后来手误隐藏了）
