### ISSUE TITLE
我想问一下，这个自动跟新或者说你们这个软件会不会影响我的hosts文件的设置

### ISSUE THREAD

**Issue by jielade2008** [cgsss/forum#5]
我想问一下，这个自动跟新或者说你们这个软件会不会影响我的hosts文件的设置，为什么自从我用过自动跟新后，我之前屏蔽的软件破解网址都失效了呢

**Comment by cgsss** [comment]
你说的是订阅更新吧？自动更新只会去对软件目录下的gui-config.json文件进行修改，跟host文件没什么关系
