### ISSUE TITLE
唯独Youtube的搜索一直报IP异常。地址栏更改为IPV6依然无效。

### ISSUE THREAD

**Issue by huang9012** [cgsss/forum#50]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

Win 10 最新版本系统，Chrome最新版本浏览器，IP自动获取，Google搜索都正常，唯独Youtube的搜索一直报IP异常。地址栏更改为IPV6依然无效。

忍了好久了，现在越来越频繁，真不知道怎么弄了，以前还没用，不知道是不是人用多了的缘故，请教下改如何解决。

**Comment by cgsss** [comment]
这个是因为有人曾经用这个ip去youtube做了爬虫，然后youtube把这个ip识别为了计算机，然后就造成在youtbe上搜索会提示人机验证的现象，唯一办法就是更换没有被识别的ip，但我们买的vps ip不是可以随便换的，即使换新的节点也可能 会出现这个情况，你先试试用其他节点，看是否依然出现这个情况，ipv6只是针对google主页有效，youtube是没有效果的。

**Comment by huang9012** [comment]
@cgsss 难道没办法解决吗？或者通过其他方式中介来搜索youtube。有时候试其他节点是可以的，但有时候每个节点都不行，我就很无奈了啊。难道买办法解决吗？好难受啊。

**Comment by huang9012** [comment]
@cgsss  难道没办法解决吗？有时候试其他节点是可以的，但有时候每个节点都不行，我就很无奈了啊。难道没办法可以解决吗？好难受啊。

**Comment by cgsss** [comment]
只有换ip，但购买的节点ip都是随机分配的，而且不可能提前知道这个ip是不是被人曾经拿来做过youtube的爬虫。

**Comment by cgsss** [comment]
跟你说的使用的人多了，可能也有点关系，但youtube的人机验证，这个问题一直存在的。

**Comment by huang9012** [comment]
他要是出人机验证我还真的挺高兴的，无非多了个步骤。关键他什么都不出。那个人机验证都是随机出现的。有的节点出，有的节点不出

**Comment by cgsss** [comment]
那你的情况不是人机验证？我主要是说这个人机验证，你可以截下图呢

**Comment by huang9012** [comment]
我换了其他节点现在又好了，如果出现了，到时候截图告诉你。我每天都要换好几次节点来使用youtube的搜索。

**Comment by cgsss** [comment]
你关了节点均衡？把这个关掉，就不会频繁出现了，开启节点均衡的话，你的账户会随机切到延迟最低的节点上，本来你上个节点已经点掉了，但你换了个节点ip，就又会弹出来了。

**Comment by huang9012** [comment]
一般是这种情况，会有一个框供你进行勾选，你点选之后，基本就不会限制你了。我的是不出这个点选的框。我来回切换节点，有时候就出来这个点选框了。系统代理模式PAC。服务器的负载均衡吗？这个我是一直开着的。

**Comment by cgsss** [comment]
关了吧，我一般不开这个，开启的话会在所有节点ip上随机切换，这样会造成账户状态不稳定。没在使用教程里要求呢，主要是不一定适合所有人，有些人可能youtbe看得少就无所谓。

**Comment by huang9012** [comment]
_正好我这边有个缓存页，我给你截图下，。
![qq 20180713152118](https://user-images.githubusercontent.com/4942508/42678135-9b0d9bea-86b0-11e8-8db4-db278dfa3d5c.png)

**Comment by huang9012** [comment]
好的，那我就把他关掉了。
