### ISSUE TITLE
为何弃用QQ作为客服支持？

### ISSUE THREAD

**Issue by cgsss** [cgsss/forum#9]
简单粗暴的说：**QQ很容易被监控**

如果我们用QQ作为客服支持，用户与我们客服QQ的私人聊天记录中会频繁出现以下内容：
- VPN
- 含有我们服务器节点域名的截图

基于实名制的基本国策和各大国内平台被政府牢牢管控的尿性以及公安机关具有随时可以轻松调取国内社交平台的数据内容的权利，为防止聊天记录被作为呈堂证供，为我们能长期安全稳定的满足查看最新行业资讯并保持与前沿科技同行的基本需求，我们将长期弃用任何国内社交软件作为客服平台使用。

取而代之我们以 github + telegram 形式提供客服支持，由于telegram的信息会实时推送，到交流群里提问通常会得到立刻解决，但如果fq受阻，则本github问答区是最好的选择（因为几乎不可能被和谐）。

so，请勿给我们以前的QQ客服留言，因为您不会收到任何回复。

**Comment by crcrcc** [comment]
666
